name: Build

on: [push]

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v2
          - name: Install 3rdparty
            shell: cmd
            run: |
              call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
              bash build_thirdparty.sh
          - name: Build
            shell: cmd
            run: |
              call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
              bash build.sh
    build-linux:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Install 3rdparty
            shell: 
            run: ./build_thirdparty.sh
          - name: Build
            shell: bash
            run: ./build.sh